services:
  db:
    image: postgres:16-alpine
    container_name: battle-royale-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: battleroyale
    ports:
      - '5433:5432'
    volumes:
      - battle-royale-pgdata:/var/lib/postgresql/data

volumes:
  battle-royale-pgdata:
